### ISSUE TITLE
Steam D-Pad does not support diagonals

### ISSUE THREAD

**Issue by rym002** [rodrigorc/inputmap#4]
When clicking diagonals with D-Pad and xbox.ini there is only 1 hat is activated.

**Comment by rodrigorc** [comment]
Well, this is tricky... The thing is that the [steam] input provides exactly what the hardware gives. And the hardware just doesn't do d-pad diagonals.
Well, actually the hardware of the left pad is just like that of the right one: one single click. It is the firmware that detects where the touch is when clicking the pad and creates the up, down, left or right d-pad. In fact, if you look carefully you'll notice that the d-pad emulation is rotated around 18 degrees to the center.

We can just do the same, both for the left-pad and the right-pad, but currently the syntax is a bit cumbersome:

```
[variables]
LPadRadius=Steam.LPadTouch and hypot(Steam.LPadX, Steam.LPadY)
LPadAngle=Steam.LPadTouch and atan2(Steam.LPadY, Steam.LPadX) * (180 / pi)

[output]
ABS_HAT0X=(Steam.LPadClick and $LPadRadius > 0.5) and \
                (between($LPadAngle, -45, 45) - ($LPadAngle > 135 or $LPadAngle < -135))
ABS_HAT0Y=(Steam.LPadClick and $LPadRadius > 0.5) and \
                (between($LPadAngle, 45, 135) - between($LPadAngle, -45, -135))
```
I'm working on a few functions to make this a bit easier to write. Stay tuned...

**Comment by rym002** [comment]
You probably saw in steam there is an option for 8  way layout. I will wait for you to solve it.

**Comment by rodrigorc** [comment]
@rym002: Please take a look to the latest version where I've added a couple of new functions and updated the `xbox.ini` example accordingly to make its DPad 8-way. Now the example has the following declarations:
```
[variables]
LPolar=rotate(polar(Steam.LPadX, Steam.LPadY), deg(18))
LHAT=Steam.LPadClick and get_radius($LPolar) > 0.4
LHATAngle=65

[output]
ABS_HAT0X=($LHAT and \
                 (between_angle($LPolar, deg(-$LHATAngle), deg($LHATAngle)) - \
                  between_angle($LPolar, deg(180 - $LHATAngle), deg(-180 + $LHATAngle))))
ABS_HAT0Y=($LHAT and \
                 (between_angle($LPolar, deg(90 - $LHATAngle), deg(90 + $LHATAngle)) - \
                  between_angle($LPolar, deg(-90 - $LHATAngle), deg(-90 + $LHATAngle))))
```
It is still a bit too verbose for my taste, but I'm not sure how to make it any shorter, other than adding a dpad() function... (that, thinking while I'm writing, might just be the best idea, but left for another time).

The free parameters are as follows:
* 18: rotate the point by so many degrees to correct for that weird rotation the touchpads have.
* 0.4: the minimum radius to get a dpad movement. Clicking the center of the touchpad will not trigger a dpad button.
* 65: degrees around each of the dpad buttons. If it is 45, then they will not overlap and you will just have a 4-way dpad. Less that 45 and you will have dead zones between the 4-ways. More that 45 and you will have diagonals.

The values for these parameters are more or less what the xbox emulation of the Steam Client uses.

**Comment by rym002** [comment]
Looks like it works, jstest output shows both active.
