### ISSUE TITLE
cross compile errors

### ISSUE THREAD

**Issue by MarkusVolk** [rodrigorc/inputmap#6]
Just tried to cross compile 'inputmap' for my armv7 settop Box and had some issues:

First one was a configure error
| ERROR:
| Cannot use target lemon as a generator because it is built for the
| host machine and no exe wrapper is defined or needs_exe_wrapper is
| true. You might want to set `native: true` instead to build it for
| the build machine.

The second was thrown at do_compile
|ERROR:
| ../git/steam/fd.h:48:20: error: 'runtime_error' is not a member of 'std'

and was able to fix/workaround it like this:

```
diff --git a/meson.build b/meson.build
index d0c3ab4..0b18c0f 100644
--- a/meson.build
+++ b/meson.build
@@ -1,7 +1,7 @@
 project('inputmap', ['c', 'cpp'], default_options : ['cpp_std=gnu++11'])
 
 
-lemon_exe = executable('lemon', ['lemon/lemon.c'])
+lemon_exe = executable('lemon', ['lemon/lemon.c'], native : true)
 
 lemon = generator(lemon_exe,
   output  : ['@BASENAME@.cpp', '@BASENAME@.h'],
diff --git a/steam/fd.h b/steam/fd.h
index 42421f5..1df901a 100644
--- a/steam/fd.h
+++ b/steam/fd.h
@@ -26,6 +26,7 @@ along with inputmap.  If not, see <http://www.gnu.org/licenses/>.
 #include <unistd.h>
 #include <fcntl.h>
 #include "unique_handle.h"
+#include "stdexcept"
 
 struct FileCloser
 {
```

By the way. Thanks for your work on the steam controller. I really appreciate it a lot

**Comment by rodrigorc** [comment]
Fixed, thanks.

It is nice to know that the Steam Controller still has some love out there :-/.
